config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def show
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_area :content, size: "70x10" %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form', article: @article %>

<hr>
<%= link_to article_path(@article), class: "back" do %>
  <i class="fas fa-undo-alt"></i> Back to article
<% end %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <p class="title"> <%= link_to article.title, article_path(article) %> </p>
  <p class="content"> <%= article.content[0..100] %>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form', article: @article %>

<hr>
<%= link_to articles_path, class: "back" do %>
  <i class="fas fa-undo-alt"></i> Back to articles
<% end %>

app/views/articles/show.html.erb
<div class="article-title d-flex justify-content-between align-items-center">
  <h1><%= @article.title %></h1>
  <div class="article-options">
    <%= link_to edit_article_path(@article) do %>
      <i class="fas fa-pencil-alt"></i>
    <% end %>

    <%= link_to article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <i class="far fa-trash-alt"></i>
    <% end %>
  </div>
</div>
<hr>
<p class="content"><%= @article.content  %></p>

<hr>
<%= link_to articles_path, class: "back" do %>
  <i class="fas fa-undo-alt"></i> Back to articles
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
  </head>

  <body>
    <nav class="navbar navbar-light bg-light px-3">
      <div class="container-fluid">
        <a class="navbar-brand" href="/articles">Wikinimous</a>
        <div class="navbar-nav">
          <a class="nav-link" href="/articles/new">New Article</a>
        </div>
      </div>
    </nav>
    <div id="articles">
      <%= yield %>
    </div>

  </body>
</html>